name: deployment-promote

on:
  schedule:
    - cron: '04 04 * * *'

env:
  TERM: dumb
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  promote:
    runs-on: ubuntu-18.04
    container: menny/android_base:1.14.0
    strategy:
      matrix:
        refname: [master]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.refname }}
      - name: request-scheduled-promote
        uses: ./.github/actions/deploy-request
        with:
          sha: HEAD
          ref: ${{ matrix.refname }}
          new_deploy: false
          api_username: ${{ secrets.BOT_MASTER_RW_GITHUB_USERNAME }}
          api_token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
