---
name: deployment-promote
on:
  schedule:
    - cron: '04 04 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TERM: dumb
jobs:
  promote:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        refname: [main, release-branch-addons-v5.1-r2, release-branch-ime-v1.12-r1]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          ref: ${{ matrix.refname }}
      - uses: ./.github/actions/deploy-request
        with:
          gh_user: ${{ secrets.BOT_MASTER_RW_GITHUB_USERNAME }}
          gh_token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
          refname: "${{ matrix.refname }}"
          deploy_mode: force_promote
