---
name: contributors-lists
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TERM: dumb
  TMPDIR: "/tmp"
jobs:
  contributors-md-update:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: update contributors list
        run: |
          git config --global --add safe.directory "${PWD}"
          bazel run //js/contributors:contributors -- generate --api_token ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }} --output_file "${{ github.workspace }}/CONTRIBUTORS.md"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8.0.0
        with:
          token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
          commit-message: 'Automated Contributors List Update'
          title: 'Automated Contributors List Update'
          committer: 'Polyglot <ask@evendanan.net>'
          author: 'Polyglot <ask@evendanan.net>'
          body: 'Generated from latest git scan.'
          team-reviewers: maintainers
          branch: 'bot-pr/contributors-list-update'
          delete-branch: true
