name: localization

#always run on the default branch: master
on:
  schedule:
    - cron: '24 02 * * *'

env:
  TERM: dumb
  CROWDIN_API: ${{ secrets.CROWDIN_API }}
  TMPDIR: "/tmp"

jobs:
  localization-update:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: github_object
        env:
          GITHUB_CONTEXT_JSON: ${{ toJson(github) }}
        run: mkdir -p build/github_object && echo "${GITHUB_CONTEXT_JSON}" > build/github_object/github_object.json
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: github_object
          path: build/github_object
      - name: Upload strings from ime/app master
        run: ./scripts/upload_strings_to_crowdin_api.sh keep
      - name: Download latest translations
        run: ./scripts/update_strings_from_crowdin_api.sh build
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2.4.0
        with:
          token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
          commit-message: 'Automated Localization Update from crowdin'
          title: 'Automated Localization Update from crowdin'
          committer: 'Polyglot <ask@evendanan.net>'
          author: 'Polyglot <ask@evendanan.net>'
          body: ''
          assignees: menny
          branch: 'bot-pr/localization-update'
