---
name: localization

# always run on the default branch: main
on:
  # schedule is used to fetch new, async, translations
  schedule:
    - cron: '24 02 * * *'
  # push is used to upload new system strings
  push:
    branches:
      - main
    paths:
      - 'ime/app/src/main/res/values/strings.xml'
      - 'scripts/upload_strings_to_crowdin_api.sh'
      - 'scripts/update_strings_from_crowdin_api.sh'
      - '.github/workflows/localization_update.yml'

env:
  TERM: dumb
  CROWDIN_API: ${{ secrets.CROWDIN_API }}
  TMPDIR: "/tmp"

jobs:
  localization-update:
    runs-on: ubuntu-22.04
    container: ghcr.io/menny/android_ndk:1.20.0
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
      - name: Upload strings from ime/app main branch
        run: ./scripts/upload_strings_to_crowdin_api.sh keep
      - name: Download latest translations
        run: |
          git config --global --add safe.directory "${PWD}"
          ./scripts/update_strings_from_crowdin_api.sh build
      - name: Update force-locale list
        run: ./gradlew :ime:app:generateForceLocaleArrayResourceFile
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5.0.1
        with:
          token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
          commit-message: 'Automated Localization Update from crowdin'
          title: 'Automated Localization Update from crowdin'
          committer: 'Polyglot <ask@evendanan.net>'
          author: 'Polyglot <ask@evendanan.net>'
          body: 'Generated from latest _main_ strings and crowdin data.'
          team-reviewers: add-on-maintainers
          branch: 'bot-pr/localization-update'
          delete-branch: true
