---
name: localization
# always run on the default branch: main
on:
  # schedule is used to fetch new, async, translations
  schedule:
    - cron: '24 02 * * *'
  # push is used to upload new system strings
  push:
    branches:
      - main
    paths:
      - '**/res/values/strings.xml'
      - '.github/workflows/localization_update.yml'
      - 'js/localization_tools/**'
      - 'crowdin.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TERM: dumb
  TMPDIR: "/tmp"
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_API_PERSONAL_TOKEN }}
jobs:
  localization-update:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: fix git safe dir
        run: git config --global --add safe.directory "${PWD}"
      - name: Delete current translations
        run: bazel run //js/localization_tools -- delete --crowdinFile="$PWD/crowdin.yml"
      - name: Crowdin upload default strings
        run: bazel run //tools:crowdin -- upload --config="$PWD/crowdin.yml"
      - name: Crowdin download all translations
        run: bazel run //tools:crowdin -- download translations --all --skip-untranslated-strings --config="$PWD/crowdin.yml"
      - name: Update force-locale list
        run: |
          bazel run //js/localization_tools -- generateLocale \
              --resourcesFolder="$PWD/ime/app/src/main/res" \
              --targetFile="$PWD/ime/app/src/main/res/values/force_locale_array_generated.xml"
      - name: Fix resource files special characters
        run: bazel run //js/localization_tools -- replaceEllipsis --crowdinFile="$PWD/crowdin.yml"
      - name: Fix formatting
        run: |
          bazel run //:format
          git status
          git add .
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
          commit-message: 'Automated Localization Update from crowdin'
          title: 'Automated Localization Update from crowdin'
          committer: 'Polyglot <ask@evendanan.net>'
          author: 'Polyglot <ask@evendanan.net>'
          body: 'Generated from latest _main_ strings and crowdin data.'
          team-reviewers: add-on-maintainers
          branch: 'bot-pr/localization-update'
          delete-branch: true
