---
name: update-aosp-dictionaries
on:
  schedule:
    - cron: '30 09 * * 5'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update_aosp_dictionaries.yml'
env:
  TERM: dumb
  TMPDIR: "/tmp"
jobs:
  aosp-dictionaries-update:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: fix git permissions for creating a PR
        run: git config --global --add safe.directory "${PWD}"
      - name: update AOSP dictionaries
        run: |
          bazel run //js/update_aosp_dictionaries -- update \
            --dictionaries_archive https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+archive/refs/heads/main/dictionaries.tar.gz \
            --dictionaries_mapping "${PWD}/js/update_aosp_dictionaries/aosp_mapping.yml"
      - name: update LineageOS dictionaries
        run: |
          bazel run //js/update_aosp_dictionaries -- update \
            --dictionaries_archive https://github.com/LineageOS/android_packages_inputmethods_LatinIME/archive/refs/heads/lineage-22.2.tar.gz \
            --dictionaries_mapping "${PWD}/js/update_aosp_dictionaries/lineage_mapping.yml"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
          commit-message: 'Automated AOSP Dictionaries Update'
          title: 'Automated AOSP Dictionaries Update'
          committer: 'Polyglot <ask@evendanan.net>'
          author: 'Polyglot <ask@evendanan.net>'
          body: 'Generated from latest objects in AOSP main branch.'
          team-reviewers: maintainers
          branch: 'bot-pr/aosp-dict-update'
          delete-branch: true
